### PR TITLE
Friends

### LINKED ISSUE #49: Make Human Readbale PGP Keys
Should be done for viewing keys on User profiles.

This can be done, but first getting the pgp key, hashing into SHA1, and then using a JSON map of 2 character Hex to words.
## Examples

Generate a pgp: https://pgpkeygen.com/

Hash a pgp key to SHA1: http://www.online-convert.com/result/d45713dba3ed90979cb23211f9f81652

Get  a list of words to convert to json: https://gist.github.com/deekayen/4148741

Create a json map using the list of words: http://stackoverflow.com/questions/8757389/reading-file-line-by-line-in-go , https://gobyexample.com/writing-files

### PR DESCRIPTION
**Pull request by kuminin**
closes #49 

Tested using postman.

### CODE REVIEW

**Comment by torch2424** [comment]
Can you post an example Json for me of the result? <3

I trust you, just want to see how cool it is!

**Comment by kuminin** [comment]
``` JSON
{
  "publicKey": "ABKLAJDLDSAHDLH",
  "readableKey": "DIFFER BETWEEN SHOULD THEM SMALL DRAW MOST TURN GIVE RUN DIFFER THEY OLD CITY OUT STAND NEXT CHANGE WORK THOUGHT"
}
```
This should be the output

**Comment by torch2424** [comment]
BEAUFITUL!!!!! :'D

**Comment by torch2424** [comment]
Merging, is it on the user object

**Review by torch2424 — APPROVED** [review]
Great work! Thank you!

**Pull request merged**
